### ISSUE TITLE
importing clock picker into other components

### ISSUE THREAD

**Issue by owenBeresford** [pencilpix/vue2-clock-picker#5]
Greetings, thanks for publishing this clock picker.

In order to get this component available in other components, I needed to add a local var, so the components array worked. 
I don't need to do this for other components.  I am building a Vue GUI inside a completely different platform, so have less access to Node tools on this project.

...
let VueClockPicker=window['vue2-clock-picker']['default'];
...
let navBar=Vue({
components:[ VueClockPicker ...],
...
})

Either:
* have I over looked something in the docs?
* I should submit a documentation patch
* I could rename several things so they are valid var names, where I think the export would be automatic.

**Comment by pencilpix** [comment]
Hi @owenBeresford 
actually I'm trying to get your use case correctly. but what I got that you have to link the component itself instead of the plugin that registers the component into global Vue.

so I updated the build (v0.1.4) and now you can use the global component once you linked/imported the right file. please [see](https://github.com/pencilpix/vue2-clock-picker#installation)

if the use cases available now are not suitable for you, PR will be helpful.

btw thanks for using Vue2-clock-picker

**Comment by owenBeresford** [comment]
yes, that is a nicer way to fix the issue
